default: &default
  adapter: postgresql
  encoding: unicode
  database: olno_development
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: olno_development
  pool: 5
  username: olno
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: olno_test
  pool: 5
  username: olno
  password:
  host: localhost
